---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samisk-samtale-bestilling
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  team: personbruker
  port: 3006
  liveness:
    path: /se/samegiella/bestilling-av-samtale/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /se/samegiella/bestilling-av-samtale/api/internal/isReady
    initialDelay: 10
  ingresses:
    - https://www.nav.no/se/samegiella/bestilling-av-samtale
  accessPolicy:
    outbound:
      rules:
        - application: tilbakemeldinger-api
          namespace: personbruker
          cluster: prod-fss
      external:
        - host: tilbakemeldinger-api.prod-fss-pub.nais.io
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: '2'
      memory: 512Mi
    requests:
      memory: 256Mi
