---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samisk-samtale-bestilling
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  team: personbruker
  port: 3006
  liveness:
    path: /person/bestilling-av-samisk-samtale/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/bestilling-av-samisk-samtale/api/internal/isReady
    initialDelay: 10
  ingresses:
    - https://www.nav.no/person/bestilling-av-samisk-samtale
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  accessPolicy:
    outbound:
      rules:
        - application: tilbakemeldinger-api
          namespace: personbruker
          cluster: prod-fss
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: tilbakemeldinger-api.prod-fss-pub.nais.io
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 192Mi
