---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samisk-samtale-bestilling
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  team: personbruker
  port: 3006
  liveness:
    path: /se/samegiella/bestilling-av-samtale/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /se/samegiella/bestilling-av-samtale/api/internal/isReady
    initialDelay: 10
  ingresses:
    - https://www.dev.nav.no/se/samegiella/bestilling-av-samtale
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: '2'
      memory: 256Mi
    requests:
      memory: 256Mi
