name: Deploy to dev
on:
  workflow_dispatch

jobs:
    deploy:
        uses: ./.github/workflows/build-and-deploy.yml
        environment: dev-gcp:personbruker
        permissions:
          contents: "read"
          id-token: "write"
        with:
          environment: dev
          app_origin: "https://www.intern.dev.nav.no"
        secrets:
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
          NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
