name: Deploy to prod
on:
    release:
        types: [released]

jobs:
  deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    environment: prod-gcp:personbruker
    permissions:
      contents: "read"
      id-token: "write"
    with:
      environment: prod
      app_origin: "https://www.nav.no"
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
